# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FISHcounter_QtDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 635)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Counts_Box = QtWidgets.QGroupBox(self.centralwidget)
        self.Counts_Box.setGeometry(QtCore.QRect(10, 170, 421, 421))
        self.Counts_Box.setObjectName("Counts_Box")
        self.Trg_0 = QtWidgets.QPushButton(self.Counts_Box)
        self.Trg_0.setGeometry(QtCore.QRect(-1, 360, 63, 31))
        self.Trg_0.setStyleSheet("")
        self.Trg_0.setObjectName("Trg_0")
        self.Trg_1 = QtWidgets.QPushButton(self.Counts_Box)
        self.Trg_1.setGeometry(QtCore.QRect(69, 360, 63, 31))
        self.Trg_1.setStyleSheet("")
        self.Trg_1.setObjectName("Trg_1")
        self.Trg_2 = QtWidgets.QPushButton(self.Counts_Box)
        self.Trg_2.setGeometry(QtCore.QRect(139, 360, 63, 31))
        self.Trg_2.setStyleSheet("")
        self.Trg_2.setObjectName("Trg_2")
        self.Trg_3 = QtWidgets.QPushButton(self.Counts_Box)
        self.Trg_3.setGeometry(QtCore.QRect(209, 360, 63, 31))
        self.Trg_3.setObjectName("Trg_3")
        self.Trg_4 = QtWidgets.QPushButton(self.Counts_Box)
        self.Trg_4.setGeometry(QtCore.QRect(279, 360, 63, 31))
        self.Trg_4.setObjectName("Trg_4")
        self.Trg_5 = QtWidgets.QPushButton(self.Counts_Box)
        self.Trg_5.setGeometry(QtCore.QRect(349, 360, 63, 31))
        self.Trg_5.setObjectName("Trg_5")
        self.label_Total = QtWidgets.QLabel(self.Counts_Box)
        self.label_Total.setGeometry(QtCore.QRect(10, 20, 41, 16))
        self.label_Total.setObjectName("label_Total")
        self.CountGoal = QtWidgets.QLineEdit(self.Counts_Box)
        self.CountGoal.setGeometry(QtCore.QRect(50, 20, 61, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CountGoal.sizePolicy().hasHeightForWidth())
        self.CountGoal.setSizePolicy(sizePolicy)
        self.CountGoal.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.CountGoal.setObjectName("CountGoal")
        self.label_Current = QtWidgets.QLabel(self.Counts_Box)
        self.label_Current.setGeometry(QtCore.QRect(150, 20, 51, 16))
        self.label_Current.setObjectName("label_Current")
        self.Current_count_text = QtWidgets.QTextBrowser(self.Counts_Box)
        self.Current_count_text.setGeometry(QtCore.QRect(200, 20, 61, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Current_count_text.sizePolicy().hasHeightForWidth())
        self.Current_count_text.setSizePolicy(sizePolicy)
        self.Current_count_text.setAcceptDrops(True)
        self.Current_count_text.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Current_count_text.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Current_count_text.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Current_count_text.setObjectName("Current_count_text")
        self.progressBar = QtWidgets.QProgressBar(self.Counts_Box)
        self.progressBar.setGeometry(QtCore.QRect(10, 60, 401, 23))
        self.progressBar.setStyleSheet("")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.line = QtWidgets.QFrame(self.Counts_Box)
        self.line.setGeometry(QtCore.QRect(0, 130, 421, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.PrBar_0 = QtWidgets.QProgressBar(self.Counts_Box)
        self.PrBar_0.setGeometry(QtCore.QRect(0, 160, 61, 201))
        self.PrBar_0.setStyleSheet("")
        self.PrBar_0.setMaximum(200)
        self.PrBar_0.setProperty("value", 0)
        self.PrBar_0.setTextVisible(True)
        self.PrBar_0.setOrientation(QtCore.Qt.Vertical)
        self.PrBar_0.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.PrBar_0.setObjectName("PrBar_0")
        self.PrBar_1 = QtWidgets.QProgressBar(self.Counts_Box)
        self.PrBar_1.setGeometry(QtCore.QRect(70, 160, 61, 201))
        self.PrBar_1.setMaximum(200)
        self.PrBar_1.setProperty("value", 0)
        self.PrBar_1.setTextVisible(True)
        self.PrBar_1.setOrientation(QtCore.Qt.Vertical)
        self.PrBar_1.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.PrBar_1.setObjectName("PrBar_1")
        self.PrBar_2 = QtWidgets.QProgressBar(self.Counts_Box)
        self.PrBar_2.setGeometry(QtCore.QRect(140, 160, 61, 201))
        self.PrBar_2.setMaximum(200)
        self.PrBar_2.setProperty("value", 0)
        self.PrBar_2.setTextVisible(True)
        self.PrBar_2.setOrientation(QtCore.Qt.Vertical)
        self.PrBar_2.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.PrBar_2.setObjectName("PrBar_2")
        self.PrBar_3 = QtWidgets.QProgressBar(self.Counts_Box)
        self.PrBar_3.setGeometry(QtCore.QRect(210, 160, 61, 201))
        self.PrBar_3.setMaximum(200)
        self.PrBar_3.setProperty("value", 0)
        self.PrBar_3.setTextVisible(True)
        self.PrBar_3.setOrientation(QtCore.Qt.Vertical)
        self.PrBar_3.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.PrBar_3.setObjectName("PrBar_3")
        self.PrBar_4 = QtWidgets.QProgressBar(self.Counts_Box)
        self.PrBar_4.setGeometry(QtCore.QRect(280, 160, 61, 201))
        self.PrBar_4.setMaximum(200)
        self.PrBar_4.setProperty("value", 0)
        self.PrBar_4.setTextVisible(True)
        self.PrBar_4.setOrientation(QtCore.Qt.Vertical)
        self.PrBar_4.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.PrBar_4.setObjectName("PrBar_4")
        self.PrBar_5 = QtWidgets.QProgressBar(self.Counts_Box)
        self.PrBar_5.setGeometry(QtCore.QRect(350, 160, 61, 201))
        self.PrBar_5.setMaximum(200)
        self.PrBar_5.setProperty("value", 0)
        self.PrBar_5.setTextVisible(True)
        self.PrBar_5.setOrientation(QtCore.Qt.Vertical)
        self.PrBar_5.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.PrBar_5.setObjectName("PrBar_5")
        self.Label_0 = QtWidgets.QLabel(self.Counts_Box)
        self.Label_0.setGeometry(QtCore.QRect(0, 140, 61, 20))
        self.Label_0.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_0.setObjectName("Label_0")
        self.Label_1 = QtWidgets.QLabel(self.Counts_Box)
        self.Label_1.setGeometry(QtCore.QRect(70, 140, 61, 20))
        self.Label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_1.setObjectName("Label_1")
        self.Label_2 = QtWidgets.QLabel(self.Counts_Box)
        self.Label_2.setGeometry(QtCore.QRect(140, 140, 61, 20))
        self.Label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_2.setObjectName("Label_2")
        self.Label_3 = QtWidgets.QLabel(self.Counts_Box)
        self.Label_3.setGeometry(QtCore.QRect(210, 140, 61, 20))
        self.Label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_3.setObjectName("Label_3")
        self.Label_4 = QtWidgets.QLabel(self.Counts_Box)
        self.Label_4.setGeometry(QtCore.QRect(280, 140, 61, 20))
        self.Label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_4.setObjectName("Label_4")
        self.Label_5 = QtWidgets.QLabel(self.Counts_Box)
        self.Label_5.setGeometry(QtCore.QRect(350, 140, 61, 20))
        self.Label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_5.setObjectName("Label_5")
        self.label = QtWidgets.QLabel(self.Counts_Box)
        self.label.setGeometry(QtCore.QRect(10, 95, 31, 21))
        self.label.setObjectName("label")
        self.LastNucleus = QtWidgets.QLabel(self.Counts_Box)
        self.LastNucleus.setGeometry(QtCore.QRect(40, 95, 61, 21))
        self.LastNucleus.setObjectName("LastNucleus")
        self.UndoButton = QtWidgets.QPushButton(self.Counts_Box)
        self.UndoButton.setEnabled(False)
        self.UndoButton.setGeometry(QtCore.QRect(120, 90, 51, 31))
        self.UndoButton.setObjectName("UndoButton")
        self.ReportButton = QtWidgets.QPushButton(self.Counts_Box)
        self.ReportButton.setEnabled(True)
        self.ReportButton.setGeometry(QtCore.QRect(340, 90, 71, 31))
        self.ReportButton.setObjectName("ReportButton")
        self.ResetButton = QtWidgets.QPushButton(self.Counts_Box)
        self.ResetButton.setGeometry(QtCore.QRect(300, 15, 81, 31))
        self.ResetButton.setObjectName("ResetButton")
        self.SaveCountButton = QtWidgets.QPushButton(self.Counts_Box)
        self.SaveCountButton.setGeometry(QtCore.QRect(210, 90, 91, 31))
        self.SaveCountButton.setObjectName("SaveCountButton")
        self.LineEdit_Key1 = QtWidgets.QLineEdit(self.Counts_Box)
        self.LineEdit_Key1.setGeometry(QtCore.QRect(70, 390, 61, 21))
        self.LineEdit_Key1.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.LineEdit_Key1.setAlignment(QtCore.Qt.AlignCenter)
        self.LineEdit_Key1.setObjectName("LineEdit_Key1")
        self.LineEdit_Key2 = QtWidgets.QLineEdit(self.Counts_Box)
        self.LineEdit_Key2.setGeometry(QtCore.QRect(140, 390, 61, 21))
        self.LineEdit_Key2.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.LineEdit_Key2.setAlignment(QtCore.Qt.AlignCenter)
        self.LineEdit_Key2.setObjectName("LineEdit_Key2")
        self.LineEdit_Key3 = QtWidgets.QLineEdit(self.Counts_Box)
        self.LineEdit_Key3.setGeometry(QtCore.QRect(210, 390, 61, 21))
        self.LineEdit_Key3.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.LineEdit_Key3.setAlignment(QtCore.Qt.AlignCenter)
        self.LineEdit_Key3.setObjectName("LineEdit_Key3")
        self.LineEdit_Key4 = QtWidgets.QLineEdit(self.Counts_Box)
        self.LineEdit_Key4.setGeometry(QtCore.QRect(280, 390, 61, 21))
        self.LineEdit_Key4.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.LineEdit_Key4.setAlignment(QtCore.Qt.AlignCenter)
        self.LineEdit_Key4.setObjectName("LineEdit_Key4")
        self.LineEdit_Key5 = QtWidgets.QLineEdit(self.Counts_Box)
        self.LineEdit_Key5.setGeometry(QtCore.QRect(350, 390, 61, 21))
        self.LineEdit_Key5.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.LineEdit_Key5.setAlignment(QtCore.Qt.AlignCenter)
        self.LineEdit_Key5.setObjectName("LineEdit_Key5")
        self.LineEdit_Key0 = QtWidgets.QLineEdit(self.Counts_Box)
        self.LineEdit_Key0.setGeometry(QtCore.QRect(0, 390, 61, 21))
        self.LineEdit_Key0.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.LineEdit_Key0.setAlignment(QtCore.Qt.AlignCenter)
        self.LineEdit_Key0.setObjectName("LineEdit_Key0")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 0, 421, 121))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 411, 25))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Preset_0 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Preset_0.setMaximumSize(QtCore.QSize(128, 23))
        self.Preset_0.setObjectName("Preset_0")
        self.horizontalLayout.addWidget(self.Preset_0)
        self.Preset_1 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Preset_1.setObjectName("Preset_1")
        self.horizontalLayout.addWidget(self.Preset_1)
        self.Preset_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Preset_2.setObjectName("Preset_2")
        self.horizontalLayout.addWidget(self.Preset_2)
        self.Preset_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Preset_3.setObjectName("Preset_3")
        self.horizontalLayout.addWidget(self.Preset_3)
        self.Preset_4 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Preset_4.setObjectName("Preset_4")
        self.horizontalLayout.addWidget(self.Preset_4)
        self.Preset_5 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Preset_5.setObjectName("Preset_5")
        self.horizontalLayout.addWidget(self.Preset_5)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 55, 41, 21))
        self.label_3.setObjectName("label_3")
        self.PresetDescButton = QtWidgets.QPushButton(self.groupBox)
        self.PresetDescButton.setGeometry(QtCore.QRect(50, 55, 331, 23))
        self.PresetDescButton.setStyleSheet("Text-align:left;")
        self.PresetDescButton.setObjectName("PresetDescButton")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(322, 95, 31, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(214, 95, 31, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(108, 95, 31, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(10, 95, 31, 16))
        self.label_10.setObjectName("label_10")
        self.BlueButton = QtWidgets.QPushButton(self.groupBox)
        self.BlueButton.setGeometry(QtCore.QRect(39, 90, 61, 23))
        self.BlueButton.setText("")
        self.BlueButton.setObjectName("BlueButton")
        self.AquaButton = QtWidgets.QPushButton(self.groupBox)
        self.AquaButton.setGeometry(QtCore.QRect(145, 90, 61, 23))
        self.AquaButton.setText("")
        self.AquaButton.setObjectName("AquaButton")
        self.GreenButton = QtWidgets.QPushButton(self.groupBox)
        self.GreenButton.setGeometry(QtCore.QRect(253, 90, 61, 23))
        self.GreenButton.setText("")
        self.GreenButton.setObjectName("GreenButton")
        self.RedButton = QtWidgets.QPushButton(self.groupBox)
        self.RedButton.setGeometry(QtCore.QRect(350, 90, 61, 23))
        self.RedButton.setText("")
        self.RedButton.setObjectName("RedButton")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setEnabled(True)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 120, 421, 51))
        self.groupBox_2.setObjectName("groupBox_2")
        self.SoundButton = QtWidgets.QPushButton(self.groupBox_2)
        self.SoundButton.setGeometry(QtCore.QRect(180, 22, 81, 21))
        self.SoundButton.setObjectName("SoundButton")
        self.SoundComboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.SoundComboBox.setEnabled(True)
        self.SoundComboBox.setGeometry(QtCore.QRect(270, 21, 141, 21))
        self.SoundComboBox.setObjectName("SoundComboBox")
        self.SoundComboBox.addItem("")
        self.SoundComboBox.addItem("")
        self.SoundComboBox.addItem("")
        self.SoundComboBox.addItem("")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton.setGeometry(QtCore.QRect(20, 20, 141, 23))
        self.pushButton.setObjectName("pushButton")
        self.ExpandButton = QtWidgets.QPushButton(self.centralwidget)
        self.ExpandButton.setGeometry(QtCore.QRect(434, 5, 16, 581))
        self.ExpandButton.setObjectName("ExpandButton")
        self.PresetDesc = QtWidgets.QLineEdit(self.centralwidget)
        self.PresetDesc.setEnabled(False)
        self.PresetDesc.setGeometry(QtCore.QRect(560, 140, 331, 20))
        self.PresetDesc.setObjectName("PresetDesc")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(460, 110, 101, 21))
        self.label_2.setObjectName("label_2")
        self.PresetLabel = QtWidgets.QLineEdit(self.centralwidget)
        self.PresetLabel.setEnabled(False)
        self.PresetLabel.setGeometry(QtCore.QRect(560, 110, 61, 20))
        self.PresetLabel.setObjectName("PresetLabel")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(460, 140, 101, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(460, 210, 101, 21))
        self.label_5.setObjectName("label_5")
        self.Trg_0_string = QtWidgets.QLineEdit(self.centralwidget)
        self.Trg_0_string.setEnabled(False)
        self.Trg_0_string.setGeometry(QtCore.QRect(460, 240, 61, 20))
        self.Trg_0_string.setObjectName("Trg_0_string")
        self.Trg_1_string = QtWidgets.QLineEdit(self.centralwidget)
        self.Trg_1_string.setEnabled(False)
        self.Trg_1_string.setGeometry(QtCore.QRect(460, 300, 61, 20))
        self.Trg_1_string.setObjectName("Trg_1_string")
        self.Trg_2_string = QtWidgets.QLineEdit(self.centralwidget)
        self.Trg_2_string.setEnabled(False)
        self.Trg_2_string.setGeometry(QtCore.QRect(460, 360, 61, 20))
        self.Trg_2_string.setObjectName("Trg_2_string")
        self.Trg_3_string = QtWidgets.QLineEdit(self.centralwidget)
        self.Trg_3_string.setEnabled(False)
        self.Trg_3_string.setGeometry(QtCore.QRect(460, 420, 61, 20))
        self.Trg_3_string.setObjectName("Trg_3_string")
        self.Trg_4_string = QtWidgets.QLineEdit(self.centralwidget)
        self.Trg_4_string.setEnabled(False)
        self.Trg_4_string.setGeometry(QtCore.QRect(460, 480, 61, 20))
        self.Trg_4_string.setObjectName("Trg_4_string")
        self.Trg_5_string = QtWidgets.QLineEdit(self.centralwidget)
        self.Trg_5_string.setEnabled(False)
        self.Trg_5_string.setGeometry(QtCore.QRect(460, 540, 61, 20))
        self.Trg_5_string.setObjectName("Trg_5_string")
        self.LockCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.LockCheckBox.setGeometry(QtCore.QRect(470, 75, 131, 20))
        self.LockCheckBox.setChecked(True)
        self.LockCheckBox.setObjectName("LockCheckBox")
        self.ShowReportButton = QtWidgets.QPushButton(self.centralwidget)
        self.ShowReportButton.setEnabled(True)
        self.ShowReportButton.setGeometry(QtCore.QRect(610, 10, 121, 51))
        self.ShowReportButton.setObjectName("ShowReportButton")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(740, 10, 151, 81))
        self.label_6.setTextFormat(QtCore.Qt.PlainText)
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.Trg_0_ISCN = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.Trg_0_ISCN.setEnabled(False)
        self.Trg_0_ISCN.setGeometry(QtCore.QRect(530, 240, 261, 41))
        self.Trg_0_ISCN.setObjectName("Trg_0_ISCN")
        self.Trg_1_ISCN = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.Trg_1_ISCN.setEnabled(False)
        self.Trg_1_ISCN.setGeometry(QtCore.QRect(530, 300, 261, 41))
        self.Trg_1_ISCN.setObjectName("Trg_1_ISCN")
        self.Trg_2_ISCN = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.Trg_2_ISCN.setEnabled(False)
        self.Trg_2_ISCN.setGeometry(QtCore.QRect(530, 360, 261, 41))
        self.Trg_2_ISCN.setObjectName("Trg_2_ISCN")
        self.Trg_3_ISCN = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.Trg_3_ISCN.setEnabled(False)
        self.Trg_3_ISCN.setGeometry(QtCore.QRect(530, 420, 261, 41))
        self.Trg_3_ISCN.setObjectName("Trg_3_ISCN")
        self.Trg_4_ISCN = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.Trg_4_ISCN.setEnabled(False)
        self.Trg_4_ISCN.setGeometry(QtCore.QRect(530, 480, 261, 41))
        self.Trg_4_ISCN.setObjectName("Trg_4_ISCN")
        self.Trg_5_ISCN = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.Trg_5_ISCN.setEnabled(False)
        self.Trg_5_ISCN.setGeometry(QtCore.QRect(530, 540, 261, 41))
        self.Trg_5_ISCN.setObjectName("Trg_5_ISCN")
        self.ChimerismCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.ChimerismCheckBox.setEnabled(True)
        self.ChimerismCheckBox.setGeometry(QtCore.QRect(810, 210, 71, 17))
        self.ChimerismCheckBox.setObjectName("ChimerismCheckBox")
        self.HiddenFocus = QtWidgets.QPushButton(self.centralwidget)
        self.HiddenFocus.setGeometry(QtCore.QRect(470, 10, 121, 51))
        self.HiddenFocus.setText("")
        self.HiddenFocus.setObjectName("HiddenFocus")
        self.SaveButton = QtWidgets.QPushButton(self.centralwidget)
        self.SaveButton.setGeometry(QtCore.QRect(470, 10, 121, 51))
        self.SaveButton.setObjectName("SaveButton")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(460, 175, 31, 16))
        self.label_14.setObjectName("label_14")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(780, 175, 31, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(670, 175, 31, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(560, 175, 31, 16))
        self.label_13.setObjectName("label_13")
        self.BlueLine = QtWidgets.QLineEdit(self.centralwidget)
        self.BlueLine.setEnabled(False)
        self.BlueLine.setGeometry(QtCore.QRect(490, 170, 61, 21))
        self.BlueLine.setObjectName("BlueLine")
        self.AquaLine = QtWidgets.QLineEdit(self.centralwidget)
        self.AquaLine.setEnabled(False)
        self.AquaLine.setGeometry(QtCore.QRect(600, 170, 61, 21))
        self.AquaLine.setObjectName("AquaLine")
        self.GreenLine = QtWidgets.QLineEdit(self.centralwidget)
        self.GreenLine.setEnabled(False)
        self.GreenLine.setGeometry(QtCore.QRect(710, 170, 61, 21))
        self.GreenLine.setObjectName("GreenLine")
        self.RedLine = QtWidgets.QLineEdit(self.centralwidget)
        self.RedLine.setEnabled(False)
        self.RedLine.setGeometry(QtCore.QRect(810, 170, 61, 21))
        self.RedLine.setObjectName("RedLine")
        self.ChimerismWidget = QtWidgets.QWidget(self.centralwidget)
        self.ChimerismWidget.setGeometry(QtCore.QRect(810, 240, 71, 341))
        self.ChimerismWidget.setObjectName("ChimerismWidget")
        self.ChimGB_0 = QtWidgets.QGroupBox(self.ChimerismWidget)
        self.ChimGB_0.setEnabled(True)
        self.ChimGB_0.setGeometry(QtCore.QRect(0, 0, 71, 41))
        self.ChimGB_0.setTitle("")
        self.ChimGB_0.setObjectName("ChimGB_0")
        self.Chim_0_b = QtWidgets.QRadioButton(self.ChimGB_0)
        self.Chim_0_b.setGeometry(QtCore.QRect(40, 10, 31, 17))
        self.Chim_0_b.setChecked(False)
        self.Chim_0_b.setObjectName("Chim_0_b")
        self.Chim_0_a = QtWidgets.QRadioButton(self.ChimGB_0)
        self.Chim_0_a.setGeometry(QtCore.QRect(10, 10, 31, 17))
        self.Chim_0_a.setChecked(True)
        self.Chim_0_a.setObjectName("Chim_0_a")
        self.Chim_0_b.raise_()
        self.Chim_0_a.raise_()
        self.ChimGB_5 = QtWidgets.QGroupBox(self.ChimerismWidget)
        self.ChimGB_5.setEnabled(True)
        self.ChimGB_5.setGeometry(QtCore.QRect(0, 300, 71, 41))
        self.ChimGB_5.setTitle("")
        self.ChimGB_5.setObjectName("ChimGB_5")
        self.Chim_5_b = QtWidgets.QRadioButton(self.ChimGB_5)
        self.Chim_5_b.setGeometry(QtCore.QRect(40, 10, 31, 17))
        self.Chim_5_b.setObjectName("Chim_5_b")
        self.Chim_5_a = QtWidgets.QRadioButton(self.ChimGB_5)
        self.Chim_5_a.setGeometry(QtCore.QRect(10, 10, 31, 17))
        self.Chim_5_a.setChecked(True)
        self.Chim_5_a.setObjectName("Chim_5_a")
        self.ChimGB_4 = QtWidgets.QGroupBox(self.ChimerismWidget)
        self.ChimGB_4.setEnabled(True)
        self.ChimGB_4.setGeometry(QtCore.QRect(0, 240, 71, 41))
        self.ChimGB_4.setTitle("")
        self.ChimGB_4.setObjectName("ChimGB_4")
        self.Chim_4_b = QtWidgets.QRadioButton(self.ChimGB_4)
        self.Chim_4_b.setGeometry(QtCore.QRect(40, 10, 31, 17))
        self.Chim_4_b.setObjectName("Chim_4_b")
        self.Chim_4_a = QtWidgets.QRadioButton(self.ChimGB_4)
        self.Chim_4_a.setGeometry(QtCore.QRect(10, 10, 31, 17))
        self.Chim_4_a.setChecked(True)
        self.Chim_4_a.setObjectName("Chim_4_a")
        self.ChimGB_2 = QtWidgets.QGroupBox(self.ChimerismWidget)
        self.ChimGB_2.setEnabled(True)
        self.ChimGB_2.setGeometry(QtCore.QRect(0, 120, 71, 41))
        self.ChimGB_2.setTitle("")
        self.ChimGB_2.setObjectName("ChimGB_2")
        self.Chim_2_b = QtWidgets.QRadioButton(self.ChimGB_2)
        self.Chim_2_b.setGeometry(QtCore.QRect(40, 10, 31, 17))
        self.Chim_2_b.setObjectName("Chim_2_b")
        self.Chim_2_a = QtWidgets.QRadioButton(self.ChimGB_2)
        self.Chim_2_a.setGeometry(QtCore.QRect(10, 10, 31, 17))
        self.Chim_2_a.setChecked(True)
        self.Chim_2_a.setObjectName("Chim_2_a")
        self.ChimGB_3 = QtWidgets.QGroupBox(self.ChimerismWidget)
        self.ChimGB_3.setEnabled(True)
        self.ChimGB_3.setGeometry(QtCore.QRect(0, 180, 71, 41))
        self.ChimGB_3.setTitle("")
        self.ChimGB_3.setObjectName("ChimGB_3")
        self.Chim_3_b = QtWidgets.QRadioButton(self.ChimGB_3)
        self.Chim_3_b.setGeometry(QtCore.QRect(40, 10, 31, 17))
        self.Chim_3_b.setObjectName("Chim_3_b")
        self.Chim_3_a = QtWidgets.QRadioButton(self.ChimGB_3)
        self.Chim_3_a.setGeometry(QtCore.QRect(10, 10, 31, 17))
        self.Chim_3_a.setChecked(True)
        self.Chim_3_a.setObjectName("Chim_3_a")
        self.ChimGB_1 = QtWidgets.QGroupBox(self.ChimerismWidget)
        self.ChimGB_1.setEnabled(True)
        self.ChimGB_1.setGeometry(QtCore.QRect(0, 60, 71, 41))
        self.ChimGB_1.setTitle("")
        self.ChimGB_1.setObjectName("ChimGB_1")
        self.Chim_1_b = QtWidgets.QRadioButton(self.ChimGB_1)
        self.Chim_1_b.setGeometry(QtCore.QRect(40, 10, 31, 17))
        self.Chim_1_b.setObjectName("Chim_1_b")
        self.Chim_1_a = QtWidgets.QRadioButton(self.ChimGB_1)
        self.Chim_1_a.setGeometry(QtCore.QRect(10, 10, 31, 17))
        self.Chim_1_a.setChecked(True)
        self.Chim_1_a.setObjectName("Chim_1_a")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionTest = QtWidgets.QAction(MainWindow)
        self.actionTest.setObjectName("actionTest")
        self.actionLoad_settings = QtWidgets.QAction(MainWindow)
        self.actionLoad_settings.setObjectName("actionLoad_settings")
        self.actionSave_settings = QtWidgets.QAction(MainWindow)
        self.actionSave_settings.setObjectName("actionSave_settings")
        self.actionLoad_FISH_count = QtWidgets.QAction(MainWindow)
        self.actionLoad_FISH_count.setObjectName("actionLoad_FISH_count")
        self.actionSave_FISH_count = QtWidgets.QAction(MainWindow)
        self.actionSave_FISH_count.setObjectName("actionSave_FISH_count")
        self.actionLoadSettings = QtWidgets.QAction(MainWindow)
        self.actionLoadSettings.setObjectName("actionLoadSettings")
        self.actionSaveSettings = QtWidgets.QAction(MainWindow)
        self.actionSaveSettings.setObjectName("actionSaveSettings")
        self.actionAlter_settings = QtWidgets.QAction(MainWindow)
        self.actionAlter_settings.setObjectName("actionAlter_settings")
        self.actionDefault = QtWidgets.QAction(MainWindow)
        self.actionDefault.setObjectName("actionDefault")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.menuFile.addAction(self.actionSave_FISH_count)
        self.menuFile.addAction(self.actionLoad_FISH_count)
        self.menuSettings.addAction(self.actionLoadSettings)
        self.menuSettings.addAction(self.actionSaveSettings)
        self.menuSettings.addAction(self.actionSave_as)
        self.menuSettings.addAction(self.actionDefault)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FISH Counter v0.1"))
        self.Counts_Box.setTitle(_translate("MainWindow", "Counts"))
        self.Trg_0.setText(_translate("MainWindow", "1R2G2A"))
        self.Trg_1.setText(_translate("MainWindow", "2R2G"))
        self.Trg_2.setText(_translate("MainWindow", "3R2F"))
        self.Trg_3.setText(_translate("MainWindow", "4R2G1A"))
        self.Trg_4.setText(_translate("MainWindow", "5R3F"))
        self.Trg_5.setText(_translate("MainWindow", "6R4F"))
        self.label_Total.setText(_translate("MainWindow", "Total:"))
        self.CountGoal.setText(_translate("MainWindow", "200"))
        self.label_Current.setText(_translate("MainWindow", "Current:"))
        self.Current_count_text.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>"))
        self.PrBar_0.setFormat(_translate("MainWindow", "%v"))
        self.PrBar_1.setFormat(_translate("MainWindow", "%v"))
        self.PrBar_2.setFormat(_translate("MainWindow", "%v"))
        self.PrBar_3.setFormat(_translate("MainWindow", "%v"))
        self.PrBar_4.setFormat(_translate("MainWindow", "%v"))
        self.PrBar_5.setFormat(_translate("MainWindow", "%v"))
        self.Label_0.setText(_translate("MainWindow", "0.0%"))
        self.Label_1.setText(_translate("MainWindow", "0.0%"))
        self.Label_2.setText(_translate("MainWindow", "0.0%"))
        self.Label_3.setText(_translate("MainWindow", "0.0%"))
        self.Label_4.setText(_translate("MainWindow", "0.0%"))
        self.Label_5.setText(_translate("MainWindow", "0.0%"))
        self.label.setText(_translate("MainWindow", "Last:"))
        self.LastNucleus.setText(_translate("MainWindow", "-"))
        self.UndoButton.setText(_translate("MainWindow", "Undo"))
        self.ReportButton.setToolTip(_translate("MainWindow", "Open the ISCN report interface"))
        self.ReportButton.setText(_translate("MainWindow", "REPORT >"))
        self.ResetButton.setText(_translate("MainWindow", "RESET"))
        self.SaveCountButton.setToolTip(_translate("MainWindow", "Save all settings plus the current count"))
        self.SaveCountButton.setText(_translate("MainWindow", "SAVE COUNT"))
        self.LineEdit_Key1.setText(_translate("MainWindow", "2"))
        self.LineEdit_Key2.setText(_translate("MainWindow", "3"))
        self.LineEdit_Key3.setText(_translate("MainWindow", "4"))
        self.LineEdit_Key4.setText(_translate("MainWindow", "5"))
        self.LineEdit_Key5.setText(_translate("MainWindow", "6"))
        self.LineEdit_Key0.setText(_translate("MainWindow", "1"))
        self.groupBox.setTitle(_translate("MainWindow", "Presets"))
        self.Preset_0.setText(_translate("MainWindow", "Bt0_nm"))
        self.Preset_1.setText(_translate("MainWindow", "Bt1_nm"))
        self.Preset_2.setText(_translate("MainWindow", "Bt2_nm"))
        self.Preset_3.setText(_translate("MainWindow", "Bt3_nm"))
        self.Preset_4.setText(_translate("MainWindow", "Bt4_nm"))
        self.Preset_5.setText(_translate("MainWindow", "Bt5_nm"))
        self.label_3.setText(_translate("MainWindow", "Desc:"))
        self.PresetDescButton.setText(_translate("MainWindow", "Preset description"))
        self.label_7.setText(_translate("MainWindow", "Red:"))
        self.label_8.setText(_translate("MainWindow", "Green:"))
        self.label_9.setText(_translate("MainWindow", "Aqua:"))
        self.label_10.setText(_translate("MainWindow", "Blue:"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Audio settings"))
        self.SoundButton.setText(_translate("MainWindow", "Sound: ON"))
        self.SoundComboBox.setItemText(0, _translate("MainWindow", "Single tone"))
        self.SoundComboBox.setItemText(1, _translate("MainWindow", "Music Scale"))
        self.SoundComboBox.setItemText(2, _translate("MainWindow", "Sequence-specific tones"))
        self.SoundComboBox.setItemText(3, _translate("MainWindow", "Mario"))
        self.pushButton.setText(_translate("MainWindow", "Start voice control module"))
        self.ExpandButton.setText(_translate("MainWindow", "<"))
        self.PresetDesc.setText(_translate("MainWindow", "Preset description"))
        self.label_2.setText(_translate("MainWindow", "Probe short name:"))
        self.label_4.setText(_translate("MainWindow", "Probe description:"))
        self.label_5.setText(_translate("MainWindow", "ISCN strings:"))
        self.LockCheckBox.setText(_translate("MainWindow", "LOCK PROBE STRINGS"))
        self.ShowReportButton.setToolTip(_translate("MainWindow", "Open the ISCN report interface"))
        self.ShowReportButton.setText(_translate("MainWindow", "SHOW REPORT"))
        self.label_6.setText(_translate("MainWindow", "The ISCN auto-report is offered as-is, according to the strings provided by the user. Please verify the correctness of the text before using it in official documents."))
        self.ChimerismCheckBox.setToolTip(_translate("MainWindow", "Not yet implemented"))
        self.ChimerismCheckBox.setText(_translate("MainWindow", "Chimerism"))
        self.SaveButton.setToolTip(_translate("MainWindow", "Save interface settings (everything except the current count)"))
        self.SaveButton.setText(_translate("MainWindow", "SAVE ALL SETTINGS"))
        self.label_14.setText(_translate("MainWindow", "Blue:"))
        self.label_11.setText(_translate("MainWindow", "Red:"))
        self.label_12.setText(_translate("MainWindow", "Green:"))
        self.label_13.setText(_translate("MainWindow", "Aqua:"))
        self.Chim_0_b.setText(_translate("MainWindow", "b"))
        self.Chim_0_a.setText(_translate("MainWindow", "a"))
        self.Chim_5_b.setText(_translate("MainWindow", "b"))
        self.Chim_5_a.setText(_translate("MainWindow", "a"))
        self.Chim_4_b.setText(_translate("MainWindow", "b"))
        self.Chim_4_a.setText(_translate("MainWindow", "a"))
        self.Chim_2_b.setText(_translate("MainWindow", "b"))
        self.Chim_2_a.setText(_translate("MainWindow", "a"))
        self.Chim_3_b.setText(_translate("MainWindow", "b"))
        self.Chim_3_a.setText(_translate("MainWindow", "a"))
        self.Chim_1_b.setText(_translate("MainWindow", "b"))
        self.Chim_1_a.setText(_translate("MainWindow", "a"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.actionTest.setText(_translate("MainWindow", "Test"))
        self.actionLoad_settings.setText(_translate("MainWindow", "Load settings..."))
        self.actionSave_settings.setText(_translate("MainWindow", "Save settings..."))
        self.actionLoad_FISH_count.setText(_translate("MainWindow", "Load FISH count"))
        self.actionSave_FISH_count.setText(_translate("MainWindow", "Save FISH count as..."))
        self.actionLoadSettings.setText(_translate("MainWindow", "Load"))
        self.actionSaveSettings.setText(_translate("MainWindow", "Save"))
        self.actionAlter_settings.setText(_translate("MainWindow", "Alter settings"))
        self.actionDefault.setText(_translate("MainWindow", "Default"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as..."))

