# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Report.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ReportDialog(object):
    def setupUi(self, ReportDialog):
        ReportDialog.setObjectName("ReportDialog")
        ReportDialog.resize(392, 390)
        self.buttonBox = QtWidgets.QDialogButtonBox(ReportDialog)
        self.buttonBox.setGeometry(QtCore.QRect(300, 350, 81, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(ReportDialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 171, 21))
        self.label.setObjectName("label")
        self.ISCNStringsTextBrowser = QtWidgets.QTextBrowser(ReportDialog)
        self.ISCNStringsTextBrowser.setGeometry(QtCore.QRect(10, 200, 371, 141))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.ISCNStringsTextBrowser.setFont(font)
        self.ISCNStringsTextBrowser.setObjectName("ISCNStringsTextBrowser")
        self.label_2 = QtWidgets.QLabel(ReportDialog)
        self.label_2.setGeometry(QtCore.QRect(10, 180, 71, 21))
        self.label_2.setObjectName("label_2")
        self.TrgLabel_1 = QtWidgets.QLabel(ReportDialog)
        self.TrgLabel_1.setGeometry(QtCore.QRect(20, 40, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.TrgLabel_1.setFont(font)
        self.TrgLabel_1.setObjectName("TrgLabel_1")
        self.TrgLabel_2 = QtWidgets.QLabel(ReportDialog)
        self.TrgLabel_2.setGeometry(QtCore.QRect(20, 60, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.TrgLabel_2.setFont(font)
        self.TrgLabel_2.setObjectName("TrgLabel_2")
        self.TrgLabel_3 = QtWidgets.QLabel(ReportDialog)
        self.TrgLabel_3.setGeometry(QtCore.QRect(20, 80, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.TrgLabel_3.setFont(font)
        self.TrgLabel_3.setObjectName("TrgLabel_3")
        self.TrgLabel_4 = QtWidgets.QLabel(ReportDialog)
        self.TrgLabel_4.setGeometry(QtCore.QRect(20, 100, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.TrgLabel_4.setFont(font)
        self.TrgLabel_4.setObjectName("TrgLabel_4")
        self.TrgLabel_5 = QtWidgets.QLabel(ReportDialog)
        self.TrgLabel_5.setGeometry(QtCore.QRect(20, 120, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.TrgLabel_5.setFont(font)
        self.TrgLabel_5.setObjectName("TrgLabel_5")
        self.TrgLabel_6 = QtWidgets.QLabel(ReportDialog)
        self.TrgLabel_6.setGeometry(QtCore.QRect(20, 140, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.TrgLabel_6.setFont(font)
        self.TrgLabel_6.setObjectName("TrgLabel_6")
        self.TrgCount_1 = QtWidgets.QLabel(ReportDialog)
        self.TrgCount_1.setGeometry(QtCore.QRect(110, 40, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.TrgCount_1.setFont(font)
        self.TrgCount_1.setObjectName("TrgCount_1")
        self.TrgCount_2 = QtWidgets.QLabel(ReportDialog)
        self.TrgCount_2.setGeometry(QtCore.QRect(110, 60, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.TrgCount_2.setFont(font)
        self.TrgCount_2.setObjectName("TrgCount_2")
        self.TrgCount_3 = QtWidgets.QLabel(ReportDialog)
        self.TrgCount_3.setGeometry(QtCore.QRect(110, 80, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.TrgCount_3.setFont(font)
        self.TrgCount_3.setObjectName("TrgCount_3")
        self.TrgCount_4 = QtWidgets.QLabel(ReportDialog)
        self.TrgCount_4.setGeometry(QtCore.QRect(110, 100, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.TrgCount_4.setFont(font)
        self.TrgCount_4.setObjectName("TrgCount_4")
        self.TrgCount_5 = QtWidgets.QLabel(ReportDialog)
        self.TrgCount_5.setGeometry(QtCore.QRect(110, 120, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.TrgCount_5.setFont(font)
        self.TrgCount_5.setObjectName("TrgCount_5")
        self.TrgCount_6 = QtWidgets.QLabel(ReportDialog)
        self.TrgCount_6.setGeometry(QtCore.QRect(110, 140, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.TrgCount_6.setFont(font)
        self.TrgCount_6.setObjectName("TrgCount_6")
        self.label_3 = QtWidgets.QLabel(ReportDialog)
        self.label_3.setGeometry(QtCore.QRect(210, 15, 47, 13))
        self.label_3.setObjectName("label_3")
        self.IncludecheckBox_1 = QtWidgets.QCheckBox(ReportDialog)
        self.IncludecheckBox_1.setGeometry(QtCore.QRect(210, 40, 21, 17))
        self.IncludecheckBox_1.setText("")
        self.IncludecheckBox_1.setChecked(True)
        self.IncludecheckBox_1.setObjectName("IncludecheckBox_1")
        self.IncludecheckBox_2 = QtWidgets.QCheckBox(ReportDialog)
        self.IncludecheckBox_2.setGeometry(QtCore.QRect(210, 60, 21, 17))
        self.IncludecheckBox_2.setText("")
        self.IncludecheckBox_2.setChecked(True)
        self.IncludecheckBox_2.setObjectName("IncludecheckBox_2")
        self.IncludecheckBox_3 = QtWidgets.QCheckBox(ReportDialog)
        self.IncludecheckBox_3.setGeometry(QtCore.QRect(210, 80, 21, 17))
        self.IncludecheckBox_3.setText("")
        self.IncludecheckBox_3.setChecked(True)
        self.IncludecheckBox_3.setObjectName("IncludecheckBox_3")
        self.IncludecheckBox_4 = QtWidgets.QCheckBox(ReportDialog)
        self.IncludecheckBox_4.setGeometry(QtCore.QRect(210, 100, 21, 17))
        self.IncludecheckBox_4.setText("")
        self.IncludecheckBox_4.setChecked(True)
        self.IncludecheckBox_4.setObjectName("IncludecheckBox_4")
        self.IncludecheckBox_5 = QtWidgets.QCheckBox(ReportDialog)
        self.IncludecheckBox_5.setGeometry(QtCore.QRect(210, 120, 21, 17))
        self.IncludecheckBox_5.setText("")
        self.IncludecheckBox_5.setChecked(True)
        self.IncludecheckBox_5.setObjectName("IncludecheckBox_5")
        self.IncludecheckBox_6 = QtWidgets.QCheckBox(ReportDialog)
        self.IncludecheckBox_6.setGeometry(QtCore.QRect(210, 140, 21, 17))
        self.IncludecheckBox_6.setText("")
        self.IncludecheckBox_6.setChecked(True)
        self.IncludecheckBox_6.setObjectName("IncludecheckBox_6")

        self.retranslateUi(ReportDialog)
        self.buttonBox.accepted.connect(ReportDialog.accept)
        self.buttonBox.rejected.connect(ReportDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ReportDialog)

    def retranslateUi(self, ReportDialog):
        _translate = QtCore.QCoreApplication.translate
        ReportDialog.setWindowTitle(_translate("ReportDialog", "Report"))
        self.label.setText(_translate("ReportDialog", "Raw data, in order of frequency:"))
        self.ISCNStringsTextBrowser.setHtml(_translate("ReportDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Courier New\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">ISCN_placeholder</span></p></body></html>"))
        self.label_2.setText(_translate("ReportDialog", "ISCN string:"))
        self.TrgLabel_1.setText(_translate("ReportDialog", "1"))
        self.TrgLabel_2.setText(_translate("ReportDialog", "2"))
        self.TrgLabel_3.setText(_translate("ReportDialog", "3"))
        self.TrgLabel_4.setText(_translate("ReportDialog", "4"))
        self.TrgLabel_5.setText(_translate("ReportDialog", "5"))
        self.TrgLabel_6.setText(_translate("ReportDialog", "6"))
        self.TrgCount_1.setText(_translate("ReportDialog", "freq"))
        self.TrgCount_2.setText(_translate("ReportDialog", "freq"))
        self.TrgCount_3.setText(_translate("ReportDialog", "freq"))
        self.TrgCount_4.setText(_translate("ReportDialog", "freq"))
        self.TrgCount_5.setText(_translate("ReportDialog", "freq"))
        self.TrgCount_6.setText(_translate("ReportDialog", "freq"))
        self.label_3.setText(_translate("ReportDialog", "Include?"))

